# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

#trigger:
#- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'src/Net7Solutions/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

# https://learn.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core?view=azure-devops&tabs=dotnetfive
steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: 7.0.x
    performMultiLevelLookup: true
    includePreviewVersions: true

- task: DotNetCoreCLI@2
  displayName: 'Nuget restore'
  inputs:
    command: restore
    feedsToUse: 'select'
    projects: 'src/Net7Solutions/Net7PlaceHolder.sln'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: build
    projects: 'src/**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
